dist: trusty
sudo: required
language: ruby
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
before_install:
  - gem install bundler
  - sudo apt-get -y install sysvbanner
scriot:
  - banner `mysqld --version`
  - banner `bundle exec ruby -e 'require "active_record"; puts ActiveRecord::VERSION::STRING'`
  - bundle exec rake
gemfile:
  - gemfiles/activerecord_4.2.gemfile
env:
  - ACTIVERECORD_MYSQL_RECONNECT_ENGINE=InnoDB
  - ACTIVERECORD_MYSQL_RECONNECT_ENGINE=MyISAM
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
