dist: trusty
sudo: required
language: ruby
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
before_install:
  - gem install bundler
script:
  - mysqld --version
  - bundle exec ruby -e 'require "active_record"; puts ActiveRecord::VERSION::STRING'
  - bundle exec rake
gemfile:
  - gemfiles/activerecord_4.2.gemfile
env:
  - ACTIVERECORD_MYSQL_RECONNECT_ENGINE=InnoDB
  - ACTIVERECORD_MYSQL_RECONNECT_ENGINE=MyISAM
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
