language: ruby
rvm:
- 2.0.0
script:
- sudo apt-get -y install sysvbanner
- banner `mysqld --version`
- banner $ACTIVERECORD_MYSQL_RECONNECT_ENGINE
- bundle install -j4
- banner `bundle exec ruby -e 'require "active_record"; puts ActiveRecord::VERSION::STRING'`
- bundle exec rake
env:
- ACTIVERECORD_MYSQL_RECONNECT_ENGINE=InnoDB
