sudo: required
language: ruby
rvm:
- 2.0.0
script:
- if [ -n "$ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION" ]; then sed -i.bak "s/spec.add_dependency 'activerecord'.*/spec.add_dependency 'activerecord', '~> $ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION'/" activerecord-mysql-reconnect.gemspec; fi
- if [ -n "$ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION" -a "$ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION" "<" "4.2" ]; then sed -i.bak "s/spec.add_dependency 'mysql2'.*/spec.add_dependency 'mysql2', '~> 0.3'/" activerecord-mysql-reconnect.gemspec; fi
- sudo apt-get -y install sysvbanner
- banner `mysqld --version`
- banner $ACTIVERECORD_MYSQL_RECONNECT_ENGINE
- bundle install -j4
- banner `bundle exec ruby -e 'require "active_record"; puts ActiveRecord::VERSION::STRING'`
- bundle exec rake
env:
- ACTIVERECORD_MYSQL_RECONNECT_ENGINE=InnoDB
- ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION=3.2.19 ACTIVERECORD_MYSQL_RECONNECT_ENGINE=InnoDB
- ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION=4.0.8 ACTIVERECORD_MYSQL_RECONNECT_ENGINE=InnoDB
- ACTIVERECORD_MYSQL_RECONNECT_ENGINE=MyISAM
- ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION=3.2.19 ACTIVERECORD_MYSQL_RECONNECT_ENGINE=MyISAM
- ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION=4.0.8 ACTIVERECORD_MYSQL_RECONNECT_ENGINE=MyISAM
