dist: trusty
sudo: required
language: ruby
rvm:
  - 2.0.0
before_install:
  - gem install bundler
  - sudo apt-get -y install sysvbanner
  - if [ -n "$ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION" ]; then sed -i.bak "s/spec.add_dependency 'activerecord'.*/spec.add_dependency 'activerecord', '~> $ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION'/" activerecord-mysql-reconnect.gemspec; fi
  - if [ -n "$ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION" -a "$ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION" "<" "4.2" ]; then sed -i.bak "s/spec.add_dependency 'mysql2'.*/spec.add_dependency 'mysql2', '< 0.4'/" activerecord-mysql-reconnect.gemspec; fi
  - bundle install
before_scriot:
  - banner `mysqld --version`
  - banner $ACTIVERECORD_MYSQL_RECONNECT_ENGINE
  - banner `bundle exec ruby -e 'require "active_record"; puts ActiveRecord::VERSION::STRING'`
scriot:
  - bundle exec rake
env:
  - ACTIVERECORD_MYSQL_RECONNECT_ENGINE=InnoDB
  - ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION=3.2.19 ACTIVERECORD_MYSQL_RECONNECT_ENGINE=InnoDB
  - ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION=4.0.8 ACTIVERECORD_MYSQL_RECONNECT_ENGINE=InnoDB
  - ACTIVERECORD_MYSQL_RECONNECT_ENGINE=MyISAM
  - ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION=3.2.19 ACTIVERECORD_MYSQL_RECONNECT_ENGINE=MyISAM
  - ACTIVERECORD_MYSQL_RECONNECT_AR_VERSION=4.0.8 ACTIVERECORD_MYSQL_RECONNECT_ENGINE=MyISAM
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
